### ISSUE TITLE
admin adapter not running after container created

### ISSUE THREAD

**Issue by SchumyHao** [duffbeer2000/docker-iobroker#1]
Hi 

I meet some issue when I run this docker image in synology.

I found it seems hostname is not set OK.
Can you help me to analysis the reason of this issue?
[duffbeer2000-iobroker0521.pdf](https://github.com/duffbeer2000/docker-iobroker/files/3201363/duffbeer2000-iobroker0521.pdf)

**Comment by duffbeer2000** [comment]
Which network mode do you use? Bridged or Host? There is a bug on den diskstation with the host mode which prevents the use of sudo. Best du use a macvlan or if you don't want that bridged.

**Comment by SchumyHao** [comment]
This is caused by using net as host. I found the root cause.

1. Do you have any clue about how to fix net=host issue? I think bridge is not acceptable, there are lots of devices need different port to communicate.
2. Can you share me any docs that can config macvlan in Synology?

**Comment by SchumyHao** [comment]
I create a PR for buanet/iobroker https://github.com/buanet/docker-iobroker/pull/26. This may also work in your image.
